@startuml Use Case Diagram (MVP)

!theme mars
title Use Case Diagram (MVP)
left to right direction

skinparam roundcorner 25
skinparam actorStyle awesome

actor "**Пользователь**" as User #Pink/LightPink
actor "**Администратор**" as Admin #Salmon/LightSalmon

rectangle "Система" {
    ([US-1.1] Перевести текст песни) as UC1 #LightPink/Pink
    ([US-1.2] Подсветить блоки) as UC2 #LightPink/Pink
    ([US-1.3] Показать комментарии) as UC3 #LightPink/Pink
    ([US-1.4] Сохранить анализ) as UC4 #LightPink/Pink
    ([US-1.5] Удалить сохранённый перевод) as UC5 #LightPink/Pink
    ([US-1.7] Просмотреть демо-песни) as UC7 #LightPink/Pink
    ([US-1.6] Редактировать комментарии) as UC6 #LightSalmon/Salmon
}

User --> UC1
User --> UC2
User --> UC3
User --> UC4
User --> UC5
User --> UC7
Admin --> UC6

@enduml